# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alice Corona
description: Data Storyteller · Consultant · Trainer · Researcher
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Logo settings
logo: "/img/logo.png"
favicon: "/img/logo.png"
me: "/img/myself.svg"

# Social settings
github: ali-ce
twitter: alice_corona
medium: alice_corona
email: 8.a.c.huxl@gmail.com


# Build settings
markdown: kramdown