name: 
  en: Alice Corona
  it: Alice Corona
description: 
  en: Data & Stories
  it: Dati & Storie
exclude: [README.md]
permalink: pretty
twitter: alice_corona
facebook: alice.corona.16
github: ali-ce
medium: alice_corona
email: alice-corona@riseup.net
url: alice-corona.nl
logo: /img/logo.png
thumbnail: /img/logo-sq.png
